import Footer from '@/layout/Footer/Footer'
import './globals.css'
import Header from '@/layout/Header/Header'

export const metadata = {
	title: 'Shopee Việt Nam | Mua và Bán trên ứng dụng di động hoặc website',
	description: 'Generated by Galvin'
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className='bg-[#f5f5f5] h-screen'>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}
