import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/layout/Header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Shopee Việt Nam | Mua và Bán trên ứng dụng di động hoặc website',
	description: 'Generated by Galvin'
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Header />
				{children}
			</body>
		</html>
	)
}
